title: balch.github.io
description: My Github Pages
show_downloads: false
# theme: jekyll-theme-dinky
navigation:
  - title: Home
    url: /
  - title: Portfolio
    url: /#portfolio
  - title: Career Highlights
    url: /employment/
  - title: Balch Blog
    url: /deep-thoughts/
social:
  github: balch
  linkedin: balch
