title: balch.github.io
url: "https://balch.github.io"
description: My Virtual Soapbox
show_downloads: false
plugins:
  - jekyll-redirect-from
navigation:
  - title: Home
    url: /
  - title: Portfolio
    url: /#portfolio
  - title: Career
    url: /#career
  - title: Posts
    expandable: true
    children: posts
  - title: Orphic.fm
    url: https://orphic.fm
    image: /assets/images/posts/2026-01-03-hello-orpheus-fm/orpheus_avatar_small.webp
social:
  github: balch
  linkedin: balch
