title: balch.github.io
url: "https://balch.github.io"
description: My Virtual Soapbox
show_downloads: false
navigation:
  - title: Home
    url: /
  - title: Portfolio
    url: /#portfolio
  - title: Career
    url: /#career
  - title: Balch Bytes
    expandable: true
    children: posts
social:
  github: balch
  linkedin: balch
